export { default as Footnote } from "./Footnote/Footnote.tsx"
export { default as Picture } from "./Picture/Picture.tsx"
export { default as Section } from "./Section/Section.tsx"
export { default as Subtitle } from "./Subtitle/Subtitle.tsx"
export { default as Title } from "./Title/Title.tsx"
